Flask Total System Part/blueprints/func.py
from flask import  Blueprint,render_template,jsonify,redirect,url_for,session
from exts import mail,db
from flask import request
from models import Quotes
from sqlalchemy.sql import text
import config
import pymysql
import pandas as pd
from pyecharts.charts import *
from pyecharts import options as opts


bp = Blueprint('func',__name__,url_prefix='/')

#http://127.0.0.1:5000
@bp.route('/')
def index():
    return render_template('index.html')

@bp.route('/data/query',defaults={'page': 1}, methods=['GET', 'POST'])
@bp.route('/data/query/page/<int:page>')
def data_query(page):
    #搜索框内容模糊匹配
    content_title = request.form.get('title') #从html获取到title输入框中的内容
    content_district = request.form.get('district') #从html获取到district输入框中的内容
    content_community = request.form.get('community')  # 从html获取到community输入框中的内容
    if content_title is None:
        content_title = ""
    # 计算分页数据
    data = Quotes.query.filter(
        Quotes.title.like("%" + content_title + "%") if content_title is not None else text(''),
        Quotes.total_price.like("%" + content_district + "%") if content_district is not None else text(''),
        Quotes.unit_price.like("%" + content_community + "%") if content_community is not None else text(''),
    ).all()
    total_count = len(data)
    page_size = 50
    total_pages = (total_count + page_size - 1) // page_size
    offset = (page - 1) * page_size
    limit = page_size
    return render_template('data-query.html', data=data, offset=offset, limit=limit, page=page, total_pages=total_pages)

@bp.route('/data/display')
def data_display():
    #生成柱状图、饼图、折线图、散点图、地图
    return render_template('data-display.html')

@bp.route('/data/forecast')
def data_forecast():
    return render_template('data-forecast.html')

Flask Total System Part/blueprints/user.py
# 用户登陆注册
from flask import  Blueprint,render_template,jsonify,redirect,url_for,session,g
from exts import mail,db
from flask_mail import Message
from random import randint
from flask import request
from models import EmailCaptchaModel,UserModel,FindPasswordModel
from .forms import RegisterForm,LoginForm,FindPasswordForm
from werkzeug.security import generate_password_hash,check_password_hash

bp = Blueprint('user',__name__,url_prefix='/user')

#用户登录
@bp.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template("login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = UserModel.query.filter_by(email=email).first()
            if not user:
                str_email = "邮箱不存在或未注册！"
                print(str_email)
                return render_template('login.html',str = str_email)
            if check_password_hash(user.password, password):
                # cookie：
                # cookie中不适合存储太多的数据，只适合存储少量的数据
                # cookie一般用来存放登录授权的东西
                # flask中的session，是经过加密后存储在cookie中的
                session['user_id'] = user.id
                return redirect("/")
            else:
                str_password = "密码错误！"
                print(str_password)
                return render_template('login.html',str = str_password)
        else:
            str = form.errors
            print(str)
            return render_template('login.html', str=str)

#用户注册
# GET：从服务器上获取数据
# POST：将客户端的数据提交给服务器
@bp.route("/register", methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template("register.html")
    else:
        # 验证用户提交的邮箱和验证码是否对应且正确
        # 表单验证：flask-wtf: wtforms
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            user = UserModel(email=email, username=username, password=generate_password_hash(password))
            db.session.add(user)
            db.session.commit()
            print(user)
            return redirect(url_for("user.login"))
        else:
            print(form.errors)
            return render_template('register.html',message = form.errors)
            # return redirect(url_for("user.register"))

#忘记密码
@bp.route('/forgetPassword',methods=['GET','POST'])
def forgetPassword():
    if request.method == 'GET':
        return render_template('forgetPassword.html')
    else:
        form = FindPasswordForm(request.form)
        if form.validate():
            email = form.email.data
            user_find = UserModel.query.filter_by(email=email).first()
            if not user_find:
                str_email = "邮箱不存在或未注册！"
                print(str_email)
                return render_template('forgetPassword.html',message = str_email)
            else:
                new_password = request.form.get('newpassword')
                user_find.password = generate_password_hash(new_password)
                db.session.commit()
                message = "密码修改成功"
                return render_template('forgetPassword.html',message=message)
        else:
            print(form.errors)
            return render_template('forgetPassword.html', message=form.errors)

#退出登录
@bp.route('/logout')
def logout():
    session.clear()
    return redirect("/")

#发送邮箱注册验证码
@bp.route('/captcha/email')
def get_email_captcha():
    # /captcha/email/<email>
    # /captcha/email?email=xxx@qq.com
    email = request.args.get("email")
    captcha = randint(1000, 9999)
    # I/O操作 邮件发送与页面变化有延迟
    message = Message(subject='二手房数据网站注册申请', recipients=[email],
                      body=f'很荣幸您在本网站注册账户，您的邮箱验证码为{captcha},请不要告诉他人。\n此信息来自SH-Analysis网站')
    mail.send(message)
    #1、验证码暂存缓存方式 memcached/redis
    #2、用数据库表的方式存储
    email_captcha = EmailCaptchaModel(email=email, captcha=captcha)
    db.session.add(email_captcha)
    db.session.commit()
    # RESTful API
    # {code: 200/400/500 message: "" data: None}
    return jsonify({'code':200, 'message':'', 'data':None})

#找回密码发送邮箱验证码
@bp.route('/find/email')
def find_captcha():
    # /captcha/email/<email>
    # /captcha/email?email=xxx@qq.com
    email = request.args.get("email")
    captcha = randint(1000, 9999)
    # I/O操作 邮件发送与页面变化有延迟
    message = Message(subject='二手房数据网站找回密码', recipients=[email],
                      body=f'你正在修改用户密码，请确认是否为本人操作，您的邮箱验证码为{captcha},请不要告诉他人。\n此信息来自SH-Analysis网站')
    mail.send(message)
    #1、验证码暂存缓存方式 memcached/redis
    #2、用数据库表的方式存储
    findpassword_captcha = FindPasswordModel(email=email, captcha=captcha)
    db.session.add(findpassword_captcha)
    db.session.commit()
    # RESTful API
    # {code: 200/400/500 message: "" data: None}
    return jsonify({'code':200, 'message':'', 'data':None})

#用户个人中心
@bp.route('/message',methods=['GET','POST'])
def message():
    if request.method == 'GET':
        return render_template("message.html")
    else:
        global new_username, new_phone, new_address, new_sex, new_age
        # 从POST请求中获取表单数据
        new_username = request.form.get('username')
        new_phone = request.form.get('phone')
        new_address = request.form.get('address')
        new_sex = request.form.get('sex')
        new_age = request.form.get('age')
        #对输入内容判断
        if new_username == "":
            new_username = g.user.username
        if new_phone == "":
            new_phone = g.user.phone
        if new_address == "":
            new_address = g.user.address
        if new_sex == "":
            new_sex = g.user.sex
        if new_age == "":
            new_age = g.user.age
        # 更新用户数据
        hhh = UserModel.query.filter(UserModel.username == g.user.username).first()
        hhh.username = new_username
        hhh.phone = new_phone
        hhh.address = new_address
        hhh.sex = new_sex
        hhh.age = new_age
        db.session.commit()
        # 返回更新后的个人资料页面
        return render_template('message.html')

Flask Total System Part/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/bootstrap.4.6.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/init.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename = 'css/bootstrap.min.css') }}">
    <script src="{{ url_for('static',filename = 'js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static',filename = 'js/popper.min.js') }}"></script>
    <script src="{{ url_for('static',filename = 'js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static',filename = 'js/echarts.js') }}"></script>
    <script src="{{ url_for('static',filename = 'js/echarts-gl.js') }}"></script>
    {% block head %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="/"> <img src="{{ url_for('static',filename = 'images/logo.png') }}" width="60" height="30" class="d-inline-block align-top" alt="" >
                <b>SH-Analysis</b></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item active">
                        <a class="nav-link" href="/"><b>首页</b> <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item" style="margin-left: 40px">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('func.data_query') }}" ><b>数据查询</b></a>
                    </li>

                    <li class="nav-item" style="margin-left:40px">
                        <a class="nav-link active" href="{{ url_for('func.data_display') }}"><b>数据展示</b></a>
                    </li>
                    <li class="nav-item" style="margin-left:40px">
                        <a class="nav-link active" href="{{ url_for('func.data_forecast') }}"><b>数据预测</b></a>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"style="margin-left:40px">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                <ul class="navbar-nav" style="margin-left: 40px">
                  {% if user %}
                    <li class="nav-item">
                      <span class="nav-link"><a href="{{ url_for('user.message') }}"><b>{{ user.username }}</b></a></span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.logout') }}"><b>退出登录</b></a>
                    </li>
                  {% else %}
                    <li class="nav-item">
                      <a class="nav-link" href="{{ url_for('user.login') }}"><b>登录</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.register') }}"><b>注册</b></a>
                    </li>
                  {% endif %}
                </ul>
            </div>
        </div>
    </nav>{# 导航栏 #}
    <div class="container">{# 容器 #}
        {% block body %}{% endblock %}
    </div>
    <div class="container-fluid" style="background-color: rgba(0,0,0,0.05)">
        {% block body_display %}{% endblock %}
    </div>
</body>
<footer class="text-center border-bottom" style="margin-top: 50px">
    Copyright © 2022-2023
    <a class="footer-url" href="http://127.0.0.1:5000" target="_blank" style="margin-left:10px; margin-right: 10px">SH-Analysis</a>
    版权所有🏠
    <p>📫网站联系邮箱:sh_analysis2023@163.com</p>
</footer>{# 底部栏 #}
</html>

Flask Total System Part/templates/data-query.html
{% extends "base.html" %}

{% block title %}SH-Analysis二手房数据网站-数据查询{% endblock %}

{% block head %}
    <!--引入layui的css文件-->
    <link rel="stylesheet" href="{{ url_for('static', filename='layui/css/layui.css') }}">
{% endblock %}

{% block body %}
    <div class="layui-container" style="background-color: #ffe8a1">
        <h1 class=" text-center" style="padding: 2rem 1rem" ><strong>潍坊市各县市区二手房详情查询</strong></h1>

        <form method="post" action="{{url_for('func.data_query')}}" class="layui-col-md4 text-center" style="padding: 2rem 0.5rem">
            <input type="text" name="title" id="title" placeholder="关键词" style="width: 150px; height: 35px">
            <input type="submit" class="layui-btn layui-btn-sm" value="搜索"style="margin-left: 20px;">
        </form>
        <form method="post" action="{{url_for('func.data_query')}}" class="layui-col-md4 text-center" style="padding: 2rem 0.5rem">
            <input type="text" name="title" id="district" placeholder="地级市" style="width: 150px; height: 35px">
            <input type="submit" class="layui-btn layui-btn-sm" value="搜索"style="margin-left: 20px;">
        </form>
        <form method="post" action="{{url_for('func.data_query')}}" class="layui-col-md4 text-center" style="padding: 2rem 0.5rem">
            <input type="text" name="title" id="community" placeholder="小区" style="width: 150px; height: 35px">
            <input type="submit" class="layui-btn layui-btn-sm" value="搜索"style="margin-left: 20px;">
        </form>
        <div class="table-container" style="margin-top: 30px">
            <table class="layui-table text-center" lay-even lay-size="sm" id="lay_page" >
                <colgroup>
                    <col width="250" class="简介">
                    <col width="50" class="总价">
                    <col width="50" class="单价">
                    <col width="50" class="面积">
                    <col width="100" class="户型">
                    <col width="100" class="楼层">
                    <col width="50" class="朝向">
                    <col width="50" class="楼型">
                    <col width="50" class="地区">
                    <col width="50" class="区域">
                    <col width="100" class="小区">
                    <col width="50" class="装修">
                    <col width="50" class="电梯">
                    <col width="50" class="梯户比例">
                    <col width="50" class="房屋性质">
                </colgroup>
                <thead >
                <tr>
                    <th>简介</th>
                    <th>总价</th>
                    <th>单价</th>
                    <th>面积</th>
                    <th>户型</th>
                    <th>楼层</th>
                    <th>朝向</th>
                    <th>楼型</th>
                    <th>地区</th>
                    <th>附近区域</th>
                    <th>小区</th>
                    <th>装修</th>
                    <th>电梯</th>
                    <th>梯户比例</th>
                    <th>房屋性质</th>
                </tr>
                </thead>
                <tbody>
                {% for i in data[offset:offset+limit] %}
                    <tr>
                        <td>{{i.title}}</td>
                        <td>{{i.total_price}}</td>
                        <td>{{i.unit_price}}</td>
                        <td>{{i.square}}</td>
                        <td>{{i.size}}</td>
                        <td>{{i.floor}}</td>
                        <td>{{i.direction}}</td>
                        <td>{{i.type}}</td>
                        <td>{{i.district}}</td>
                        <td>{{i.nearby}}</td>
                        <td>{{i.community}}</td>
                        <td>{{i.decoration}}</td>
                        <td>{{i.elevator}}</td>
                        <td>{{i.elevatorNum}}</td>
                        <td>{{i.ownership}}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <nav aria-label="Page navigation" style="margin-top: 10px; margin-left: 400px; padding: 2rem 1rem; ">
                <ul class="pagination">
                    {% if page > 1 %}
                        <li class="page-item">
                            <a class="page-link" href="{{ url_for('func.data_query', page=page-1) }}">上一页</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#">上一页</a>
                        </li>
                    {% endif %}
                    {% if page <= 4 %}
                        {% for p in range(1, page + 4) %}
                            {% if p == page %}
                                <li class="page-item active"><a class="page-link" href="#">{{ p }}</a></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="{{ url_for('func.data_query', page=p) }}">{{ p }}</a></li>
                            {% endif %}
                        {% endfor %}
                    {% elif page >= (total_pages - 3) %}
                        {% for p in range(total_pages - 6, total_pages + 1) %}
                            {% if p == page %}
                                <li class="page-item active"><a class="page-link" href="#">{{ p }}</a></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="{{ url_for('func.data_query', page=p) }}">{{ p }}</a></li>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        {% for p in range(page - 2, page + 3) %}
                            {% if p == page %}
                                <li class="page-item active"><a class="page-link" href="#">{{ p }}</a></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="{{ url_for('func.data_query', page=p) }}">{{ p }}</a></li>
                            {% endif %}
                        {% endfor %}
                        <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
                        <li class="page-item"><a class="page-link" href="{{ url_for('func.data_query', page=total_pages) }}">{{ total_pages }}</a></li>
                    {% endif %}

                    {% if page < total_pages %}
                        <li class="page-item">
                            <a class="page-link" href="{{ url_for('func.data_query', page=page + 1) }}">下一页</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#">下一页</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
<!--引入layui的js库-->
<script src="{{ url_for('static',filename = 'layui/layui.js') }}"></script>
<script>
    layui.use(["table","laypage"],function () {
        var table = layui.table; //获得LayUI数据表格模块
        var laypage = layui.laypage; //获得LayUI分页模块
        table.render();
    })
</script>
{% endblock %}

Flask Total System Part/templates/forgetPassword.html
{% extends "base.html" %}

{% block title %}忘记密码{% endblock %}

{% block head %}
  <script src="{{ url_for('static', filename='js/findPassword.js') }}"></script>
{% endblock %}

{% block body %}

    <div class="container text-center" style="display: flex;flex-direction: column; margin-top: 30px">
        <form action="" method="POST">
            <p>邮箱：<input type="email" aria-describedby="emailHelp" name="email" placeholder="例如：XXX@163.com" id="exampleInputEmail1"></p>
            <p>验证码：
                <input type="text"  name="captcha" id="captcha" placeholder="四位数字"><button  type="button" id="captcha-btn">获取验证码</button>
            </p>
            <p>新密码：<input type="password" name="newpassword" id="newpassword"></p>
            <p>确认密码：<input type="password" name="password_again" id="password_again"></p>
            <div class="text-warning text-center"><h5><strong>{{ message }}</strong></h5></div>
            <button type="submit">提交</button>
        </form>

    </div>

{% endblock %}

Flask Total System Part/templates/index.html
{% extends "base.html" %}

{% block title %}SH-Analysis二手房数据网站-首页{% endblock %}

{% block head %}

{% endblock %}

{% block body %}
<div class="container-index">
    <div class="jumbotron" style="width: auto; height: 330px; margin-top: 15px; padding: 1rem 2rem;">
        <h1 class="display-4" >HELLO , SH-Analysis✨</h1>
        <p class="lead">这是一个二手房数据分析网站🖥</p>
        <hr class="my-4">
        <b>网站大致提供三个功能：特定数据查询⚙，数据可视化展示🖼，数据趋势预测🔮。</b>
        <p>在这里你可以查询各地二手房的详情信息，本网站也会提供各地二手房数据统计图，并根据您的需要进行展示，然后本网站还可以对二手房房价未来趋势做预测。</p>
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="{{ url_for('func.data_query') }}" role="button">了解更多</a>
        </p>
    </div>{# 大屏展示块 #}
    <div class="media">{# 图文混排 #}
        <div class="bd-example" style="width: 500px;height: 400px">
        <div class="alert alert-primary" role="alert" style="width: 150px; height: 50px; text-align: center">
            <h5><strong>二手房示例</strong></h5>
        </div>
        <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">{# 轮播页码效果 #}
                <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">{# 轮播图片展示 #}
                <div class="carousel-item active">
                    <a href="https://wf.lianjia.com/ershoufang/103124079075.html" target="_blank">
                        <img src="{{ url_for('static',filename = 'images/sh-wf-example.jpg') }}" class="d-block w-100" alt="...">
                    </a>
                    <div class="carousel-caption d-none d-md-block">
                        <h6 style="color: #ff0000">智群古德近，电梯三居室，全明户型 楼层好</h6>
                    </div>
                </div>
                <div class="carousel-item">
                    <a href="https://wf.lianjia.com/ershoufang/103124231516.html" target="_blank">
                        <img src="{{ url_for('static',filename = 'images/sh-wf-example2.jpg') }}" class="d-block w-100" alt="...">
                    </a>
                    <div class="carousel-caption d-none d-md-block">
                        <h6 style="color: #ff0000">上城佳乐家近，近200平的单位房，停车免费，有钥匙</h6>
                    </div>
                </div>
                <div class="carousel-item">
                    <a href="https://wf.lianjia.com/ershoufang/103124056455.html" target="_blank">
                        <img src="{{ url_for('static',filename = 'images/sh-wf-example3.jpg') }}" class="d-block w-100" alt="...">
                    </a>
                    <div class="carousel-caption d-none d-md-block">
                        <h6 style="color: #ff0000">万达隔壁 精装五室 小高层上下两层 带两个地下室</h6>
                    </div>
                </div>

            </div>
            <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>{# 轮播按钮效果 #}
            <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>

        </div>
        <div class="contaier-index-left" style="margin-top: 30px">
            <div class="alert alert-info" role="alert" style="width: 150px; height: 50px; text-align: center">
                <h5><strong>二手房讯息</strong></h5>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6>最新消息</h6>
                    <h6><b><a href="http://www.ce.cn/xwzx/gnsz/gdxw/202302/14/t20230214_38390935.shtml" target="_blank">多地持续优化房地产调控政策 部分城市二手房市场现回暖迹象</a></b></h6>
                    <h6><b><a href="http://www.ce.cn/cysc/fdc/fc/202302/16/t20230216_38395322.shtml" target="_blank">多地推行二手房“带押过户” 专家称便利交易勿忘风险</a></b></h6>
                    <h6><b><a href="http://www.ce.cn/cysc/fdc/fc/202302/16/t20230216_38396660.shtml" target="_blank">1月新房和二手房环比上涨城市增多 业内：一线城市迎“小阳春”</a></b></h6>
                    <h6><b><a href="https://news.sina.com.cn/o/2022-12-26/doc-imxxymic1277970.shtml" target="_blank">2022地产十大政策：全面松绑，需求、供给齐发力</a></b></h6>
                </div>
            </div>
            <div class="alert alert-warning" role="alert" style="width: 150px; height: 50px; text-align: center; margin-top: 20px">
                <h5><strong>词云展示</strong></h5>
            </div>
            <div class="card">
                <div class="card-body">
                    <img src="{{ url_for('static',filename='images/潍坊二手房词云图.png') }}" alt="潍坊二手房词云——高频词汇汇总" style="width: 330px; height: 420px; margin-left: 50px">
                </div>
            </div>
        </div>
    </div>{# 轮播图 #}
        <div class="media-body" style="margin-left: 50px; margin-right: 10px ;margin-top: 5px">
            <div class="alert alert-secondary" role="alert" style="width: 125px; height: 50px; text-align: center">
                <h5><strong>政策公告</strong></h5>
            </div>
            <div class="card">
                <div class="card-body">
                    <b><i>最高法提依法遏制“借名买房”“法拍房”炒作</i></b>
                    <p></p>
                    <p><i>全国高级法院院长会议日前举行，最高人民法院提出依法审理教育、医疗、养老、育幼、社会保障等民生领域案件，加大对高校毕业生、农民工、灵活就业人员等权益保护力度，维护劳动者公平就业权利。要落实“房子是用来住的、不是用来炒的”定位，依法遏制“借名买房”“法拍房”炒作。</i></p>
                    <p>点评：限购、限贷政策是阻碍一部分拥有多套房产人群的重要限制，而通过“借名买房”可以有效的规避这一政策，但是也会存在较大的风险，那么最高法出台相关政策是希望一部分通过规避政策买房人群谨慎自己的购房行为，法律对其行为是不支持的。“法拍房”也是类似情况，各地也相继出台“法拍房”的限购政策，最高法也重生房子的居住属性，以后为规避限购购买此类房产的人群也需要正视自身的购房动机。</p>
                    ——2022.1.18
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <p><b><i>5年期以上LPR 21个月以来首次下调</i></b></p>
                    <p><i>1月20日，央行最新一期LPR宣布降息。此次LPR利率中，5年期利率下调了5个基点，为4.60%，这是21个月以来首次出现5年期LPR下调的情况。以100万贷款金额、30年期等额本息还款的按揭贷款为例，在利率调整前，LPR为4.65%，此时月供额为5156元。而此次利率调整后，LPR为4.60%，此时月供额为5126元，月供额减少了约30元。</i></p>
                    <p>点评：房贷利率的下调将会降低购房者的成本支出，有利于需求的释放。单次的LPR的调整对购房者持有成本的减少是相对较少的，不过21个月首次下调LPR是释放了降息的信号，对楼市将是个长期的利好政策。</p>
                    ——2022.1.20
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <p><b><i>央行发布重磅数据！2021年末房地产贷款余额52万亿，个人住房贷款余额增速回落</i></b></p>
                    <p><i>2021年末，全国房地产贷款余额52.2万亿元，同比增长7.9%，增速比9月末提高了0.3个百分点，其中四季度房地产贷款新增7734亿元，同比多增2020亿元，较三季度多增1578亿元。房地产销售、购地、融资等行为已逐步回归常态，市场预期稳步改善。</i></p>
                    <p>点评：四季度房贷增速提升，体现出前期的金融政策已经向宽松转向。今年全国二手房市场相对低迷和各个城市调控政策相关，但信贷政策相对从紧也密不可分，因此，四季度开始的金融政策逐步放松有利于未来市场的交易。</p>
                    ——2022.1.30
                </div>
            </div>
        </div>{# 文本 #}
    </div>
</div>
{% endblock %}

Flask Total System Part/templates/login.html
{% extends "base.html" %}

{% block title %}SH-Analysis二手房数据网站-登录{% endblock %}

{% block head %}{% endblock %}

{% block body %}
<div class="row mt-4" style="height:800px ;background-image: url({{ url_for('static',filename='images/登录.jpg') }}); ">
            <div class="col"></div>
            <div class="col" style="margin-top: 200px">
                <form method="POST">
                    <div class="form-group">
                        <label for="exampleInputEmail1"><h5 class="text-warning"><b>邮箱</b></h5></label>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1"><h5 class="text-warning"><b>密码</b></h5></label>
                        <input type="password" name="password" class="form-control" id="exampleInputPassword1">
                    </div>
                    <a href="{{ url_for('user.forgetPassword') }}"><div class="text-danger"><b>忘记密码？</b></div></a>
                    <div class="text-warning text-center"><h5><strong>{{ str }}</strong></h5></div>
                    <div class="form-group" style="margin-top: 30px;">
                        <button type="submit" class="btn btn-primary btn-block">立即登录</button>
                    </div>
                </form>
            </div>
            <div class="col"></div>
        </div>
{% endblock %}